# Generated by Django 5.0.2 on 2024-04-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementtype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dataelementtype',
            name='uscdi_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
