# Generated by Django 5.0.2 on 2024-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0002_alter_dataelementtype_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('uscdi_uuid', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type: Data Class',
                'verbose_name_plural': 'Types: Data Classes',
            },
        ),
        migrations.CreateModel(
            name='DomainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('uscdi_uuid', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type: Domain',
                'verbose_name_plural': 'Types: Domains',
            },
        ),
        migrations.CreateModel(
            name='UseCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('uscdi_uuid', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type: Use Case',
                'verbose_name_plural': 'Types: Use Cases',
            },
        ),
    ]
