# Generated by Django 5.0.2 on 2024-04-21 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0003_dataclasstype_domaintype_usecasetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelementtype',
            name='additional_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='applicable_vocabulary_standards',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_ig_or_profile',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_ig_or_profile_urls',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_project',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_project_urls',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_reporting_program',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_us_core_profile',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='associated_us_core_profile_urls',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='cda_xpath',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='current_uscdi_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='data_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uscdi.dataclasstype'),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uscdi.domaintype'),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='fhir_path',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='hl7v2_path',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='in_uscdi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='submission_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='uscdi_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='use_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uscdi.usecasetype'),
        ),
        migrations.AlterField(
            model_name='dataelementtype',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
