# Generated by Django 5.0.2 on 2024-04-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0004_dataelementtype_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementtype',
            name='data_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.dataclasstype'),
        ),
        migrations.AlterField(
            model_name='dataelementtype',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.domaintype'),
        ),
        migrations.AlterField(
            model_name='dataelementtype',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.usecasetype'),
        ),
    ]
