# Generated by Django 5.0.2 on 2024-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0005_alter_dataelementtype_data_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementtype',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
