# Generated by Django 5.0.2 on 2024-06-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0006_alter_dataelementtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDCDataElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requester', models.CharField(max_length=255)),
                ('DataElementName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('In_USCDI', models.CharField(max_length=255)),
                ('If_Data_Element_Is_In_USCDI_What_Level_Is_It', models.CharField(max_length=255)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('UseCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.usecasetype')),
            ],
            options={
                'verbose_name': 'USCDI+ CDC Recommended Data Element',
                'verbose_name_plural': 'USCDI+ CDC Recommended Data Elements',
            },
        ),
    ]
