# Generated by Django 5.2.17 on 2026-09-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0007_cdcdataelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelementtype',
            name='fhir_example_value_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='fhir_example_value_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='fhir_location',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='fhir_more_details',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='hl7v2_example_value_1',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='hl7v2_example_value_2',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='hl7v2_location',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dataelementtype',
            name='hl7v2_more_details',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
    ]
