# Generated by Django 5.2.17 on 2026-09-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0008_dataelementtype_fhir_example_value_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('uscdi_uuid', models.UUIDField(blank=True, null=True)),
                ('data_class_description', models.TextField(blank=True, default='', max_length=2048)),
                ('additional_information', models.TextField(blank=True, default='')),
                ('in_uscdi', models.BooleanField(blank=True, default=False)),
                ('uscdi_url', models.URLField(blank=True, default='')),
                ('classification_level', models.CharField(blank=True, default='', max_length=255)),
                ('data_element', models.CharField(blank=True, default='', max_length=255)),
                ('data_element_description', models.TextField(blank=True, default='', max_length=2048)),
                ('applicable_standards', models.TextField(blank=True, default='', max_length=2048)),
                ('fhir_associated_ig_or_profile_urls', models.CharField(blank=True, default='', max_length=512)),
                ('fhir_associated_us_core_profile_urls', models.CharField(blank=True, default='', max_length=512)),
                ('fhir_path', models.CharField(blank=True, default='', help_text='e.g., Patient.birthDate', max_length=256)),
                ('mm_guideId', models.CharField(blank=True, default='', max_length=256)),
                ('mm_guideInternalVersion', models.CharField(blank=True, default='', max_length=256)),
                ('mm_blockId', models.CharField(blank=True, default='', max_length=256)),
                ('mm_ordinal', models.IntegerField(blank=True, default=0)),
                ('mm_name', models.CharField(blank=True, default='', max_length=256)),
                ('mm_description', models.TextField(blank=True, default='')),
                ('mm_shortName', models.CharField(blank=True, default='', max_length=256)),
                ('mm_comments', models.TextField(blank=True, default='')),
                ('mm_status', models.CharField(blank=True, default='', max_length=256)),
                ('mm_dataType', models.CharField(blank=True, default='', max_length=256)),
                ('mm_businessRules', models.TextField(blank=True, default='')),
                ('mm_isUnitOfMeasure', models.BooleanField(blank=True, default=False)),
                ('mm_codeSystem', models.CharField(blank=True, default='', max_length=256)),
                ('mm_legacyPriority', models.CharField(blank=True, default='', max_length=256)),
                ('mm_priority', models.CharField(blank=True, default='', max_length=256)),
                ('mm_isRepeat', models.BooleanField(blank=True, default=False)),
                ('mm_mayRepeat', models.BooleanField(blank=True, default=False)),
                ('mm_valueSetCode', models.CharField(blank=True, default='', max_length=256)),
                ('hl7v2_legacy_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_message_context', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_data_type', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_segment_type', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_field_position', models.IntegerField(blank=True, default=0)),
                ('hl7v2_component_position', models.IntegerField(blank=True, default=0)),
                ('hl7v2_usage', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_cardinality', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_literalFieldValues', models.TextField(blank=True, default='', max_length=2048)),
                ('hl7v2_repeatingGroupElementType', models.CharField(blank=True, default='', max_length=255)),
                ('hl7v2_sampleSegment', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.dataclasstype')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.domaintype')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uscdi.usecasetype')),
            ],
        ),
    ]
