# Generated by Django 5.2.17 on 2026-09-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0009_dataelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='applicable_vocabulary_standards',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
