# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0010_dataelement_applicable_vocabulary_standards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='mm_mayRepeat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
