# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0011_alter_dataelement_mm_mayrepeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='mm_containingBlockId',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='mm_containingGuideId',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='mm_elementId',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
