# Generated by Django 5.2.17 on 2026-09-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0012_dataelement_mmg_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='mm_containingGuideName',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='mm_containingGuideStatus',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='mm_matchMethod',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='dataelement',
            name='mm_matchScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
