# Generated by Django 5.2.17 on 2026-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0013_dataelement_mmg_match_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HL7Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('example', models.TextField(blank=True, default='', max_length=512)),
            ],
        ),
    ]
