# Generated by Django 5.2.17 on 2026-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0014_hl7segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HL7Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('example', models.TextField(blank=True, default='', max_length=512)),
                ('segments', models.ManyToManyField(blank=True, to='uscdi.hl7segment')),
            ],
        ),
    ]
