# Generated by Django 5.2.17 on 2026-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0015_hl7message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMappingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hl7message',
            name='pub_health_germain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hl7message',
            name='uscdi_elements',
            field=models.ManyToManyField(blank=True, to='uscdi.dataelement'),
        ),
        migrations.AddField(
            model_name='hl7message',
            name='mmgs',
            field=models.ManyToManyField(blank=True, to='uscdi.messagemappingguide'),
        ),
    ]
