# Generated by Django 5.2.17 on 2026-10-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscdi', '0016_messagemappingguide_hl7message_pub_health_germain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemappingguide',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='messagemappingguide',
            name='csv_guide_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messagemappingguide',
            name='hl7v2_guide_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
