# Generated by Django 5.0.2 on 2024-03-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='intermediate_system',
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='is_intermediary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='main_data_input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_main_data_input_type', to='report_metadata.healthdatatype'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='other_supported_data_input_types',
            field=models.ManyToManyField(related_name='other_dest_input_type', to='report_metadata.healthdatatype'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='source_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_system_source_system', to='report_metadata.sourcesoftware'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='main_data_output_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soure_main_data_output_type', to='report_metadata.healthdatatype'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='other_supported_data_ouput_types',
            field=models.ManyToManyField(related_name='other_supported_source_output_data_types', to='report_metadata.healthdatatype'),
        ),
        migrations.DeleteModel(
            name='IntermediarySourceSystem',
        ),
    ]
