# Generated by Django 5.0.2 on 2024-03-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0002_remove_connection_intermediate_system_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdcreceivingsoftware',
            options={'verbose_name': 'Software: CDC Receiving', 'verbose_name_plural': 'Software: CDC Receiving'},
        ),
        migrations.AlterModelOptions(
            name='cdcreceivingsystem',
            options={'verbose_name': 'System: CDC Receiving', 'verbose_name_plural': 'Systems: CDC Receiving'},
        ),
        migrations.AlterModelOptions(
            name='datatransporttype',
            options={'verbose_name': 'Type: Data Transport', 'verbose_name_plural': 'Types: Data Transports'},
        ),
        migrations.AlterModelOptions(
            name='healthdatatype',
            options={'verbose_name': 'Type: Health Data', 'verbose_name_plural': 'Types: Health Data'},
        ),
        migrations.AlterModelOptions(
            name='patientidtype',
            options={'verbose_name': 'Type: Patient ID', 'verbose_name_plural': 'Types: Patient ID'},
        ),
        migrations.AlterModelOptions(
            name='reporttype',
            options={'verbose_name': 'Type: Report', 'verbose_name_plural': 'Types: Report'},
        ),
        migrations.AlterModelOptions(
            name='sourcesoftware',
            options={'verbose_name': 'Software: Data Source', 'verbose_name_plural': 'Software: Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'verbose_name': 'System: Data Source', 'verbose_name_plural': 'Systems: Data Sources'},
        ),
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='other_supported_data_ouput_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='cdc_other_supportted_output_types', to='report_metadata.healthdatatype'),
        ),
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
