# Generated by Django 5.0.2 on 2024-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0003_alter_cdcreceivingsoftware_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdcreceivingsystem',
            old_name='main_data_output_type',
            new_name='main_data_input_type',
        ),
        migrations.RemoveField(
            model_name='cdcreceivingsystem',
            name='other_supported_data_ouput_types',
        ),
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='other_supported_data_input_types',
            field=models.ManyToManyField(blank=True, related_name='cdc_other_supported_input_types', to='report_metadata.healthdatatype'),
        ),
    ]
