# Generated by Django 5.0.2 on 2024-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0004_rename_main_data_output_type_cdcreceivingsystem_main_data_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='bscrypt_salt_strategy',
            field=models.CharField(choices=[('shared', 'Shared'), ('unique', 'Unique')], default='unique', max_length=255),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='next_origin_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='next_shared_bscrypt_salt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='origin_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='previous_origin_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='previous_origin_ids',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='previous_shared_bscrypt_salt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='rotate_origin_id',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='rotate_shared_bscrypt_salt',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='shared_bscrypt_salt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
