# Generated by Django 5.0.2 on 2024-03-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0005_jurisdiction_bscrypt_salt_strategy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='source_data_patient_id_link_hash',
            new_name='patient_id_dob_mobilephone_hash',
        ),
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='patient_safety_identifier',
            new_name='patient_insurance_member_id',
        ),
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='patient_safety_identifier_issuer',
            new_name='patient_insurance_plan_id',
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_mobile_phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_seen_identifier',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_seen_identifier_issuer',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='rmetamessage',
            name='source_patient_id_issuer',
            field=models.CharField(blank=True, default='', help_text='Assigning Authority/Issuer', max_length=200),
        ),
    ]
