# Generated by Django 5.0.2 on 2024-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0006_rename_source_data_patient_id_link_hash_rmetamessage_patient_id_dob_mobilephone_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='patient_id_dob_mobilephone_hash',
            new_name='patient_dob_mobilephone_hash',
        ),
    ]
