# Generated by Django 5.0.2 on 2024-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0007_rename_patient_id_dob_mobilephone_hash_rmetamessage_patient_dob_mobilephone_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurisdiction',
            old_name='next_shared_bscrypt_salt',
            new_name='bscrypt_salt',
        ),
        migrations.RenameField(
            model_name='jurisdiction',
            old_name='shared_bscrypt_salt',
            new_name='next_bscrypt_salt',
        ),
        migrations.RenameField(
            model_name='jurisdiction',
            old_name='previous_origin_ids',
            new_name='retired_bscrypt_salts',
        ),
        migrations.RenameField(
            model_name='jurisdiction',
            old_name='previous_shared_bscrypt_salt',
            new_name='retired_origin_ids',
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='previous_bscrypt_salt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
