# Generated by Django 5.0.2 on 2024-03-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0009_jurisdiction_bscrypt_salt_rounds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='vendor_or_contracor_poc',
            new_name='vendor_or_contractor_poc',
        ),
        migrations.RemoveField(
            model_name='cdcreceivingsystem',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='sourcesystem',
            name='cdc_destination_system',
        ),
        migrations.RemoveField(
            model_name='sourcesystem',
            name='partner',
        ),
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='main_data_input_transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.datatransporttype'),
        ),
        migrations.AddField(
            model_name='connection',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.partner'),
        ),
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='main_data_input_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.healthdatatype'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='cdc_receiving_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.cdcreceivingsystem'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='source_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.sourcesystem'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='source_system',
            field=models.ForeignKey(blank=True, help_text='Leave blank if original source (ie. not an intermediary systems)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_system_source_system', to='report_metadata.sourcesoftware'),
        ),
    ]
