# Generated by Django 5.0.2 on 2024-03-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0010_rename_vendor_or_contracor_poc_connection_vendor_or_contractor_poc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesoftware',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='other_supported_data_input_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_dest_input_type', to='report_metadata.healthdatatype'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='other_supported_data_ouput_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_supported_source_output_data_types', to='report_metadata.healthdatatype'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='source_system',
            field=models.ForeignKey(blank=True, help_text='Leave blank if original source (ie. not an intermediary system)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_system_source_system', to='report_metadata.sourcesoftware'),
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
