# Generated by Django 5.0.2 on 2024-03-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0012_alter_connection_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonyomizedDataNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('keep', models.BooleanField(blank=True)),
                ('hippa_id', models.BooleanField(blank=True)),
                ('in_syndromic_message', models.BooleanField(blank=True)),
                ('eicr_version', models.CharField(blank=True, default='', max_length=16)),
                ('eicr_data_element', models.CharField(blank=True, default='', max_length=255)),
                ('eicr_template', models.CharField(blank=True, default='', max_length=255)),
                ('eicr_xpath', models.CharField(blank=True, default='', max_length=512)),
                ('fhir_resource_version', models.CharField(blank=True, default='', max_length=512)),
                ('fhir_resource_type', models.CharField(blank=True, default='', max_length=512)),
                ('fhir_resource_path', models.CharField(blank=True, default='', max_length=512)),
                ('hl7v2_version', models.CharField(blank=True, default='', max_length=512)),
                ('hl7v2_path', models.CharField(blank=True, default='', max_length=512)),
                ('rmeta_field_name', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonyomized eICR Data Need',
                'verbose_name_plural': 'Anonyomized eICR Data Needs',
            },
        ),
    ]
