# Generated by Django 5.0.2 on 2024-03-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0015_anonyomizeddataneed_pprl_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonyomizeddataneed',
            old_name='hippa_id',
            new_name='hipaa_id',
        ),
    ]
