# Generated by Django 5.0.2 on 2024-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0016_rename_hippa_id_anonyomizeddataneed_hipaa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystem',
            name='other_supported_data_input_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_dest_input_type', to='report_metadata.healthdatatype'),
        ),
    ]
