# Generated by Django 5.0.2 on 2024-03-11 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0017_alter_sourcesystem_other_supported_data_input_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystem',
            name='main_data_output_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soure_main_data_output_type', to='report_metadata.healthdatatype'),
        ),
    ]
