# Generated by Django 5.0.2 on 2024-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0018_alter_sourcesystem_main_data_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='state_level',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='state_level',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
