# Generated by Django 5.0.2 on 2024-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0019_jurisdiction_state_level_alter_partner_state_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystem',
            name='other_supported_data_input_types',
            field=models.ManyToManyField(blank=True, related_name='other_dest_input_type', to='report_metadata.healthdatatype'),
        ),
    ]
