# Generated by Django 5.0.2 on 2024-03-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0020_alter_sourcesystem_other_supported_data_input_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='main_data_input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.healthdatatype'),
        ),
    ]
