# Generated by Django 5.0.2 on 2024-03-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0021_alter_cdcreceivingsystem_main_data_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='main_data_input_transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.datatransporttype', verbose_name='Transport Type'),
        ),
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='main_data_input_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.healthdatatype', verbose_name='Input Data Type'),
        ),
    ]
