# Generated by Django 5.0.2 on 2024-03-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0022_alter_cdcreceivingsystem_main_data_input_transport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='transport_in_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_transport_in', to='report_metadata.datatransporttype'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='transport_out_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourrce_transport_out', to='report_metadata.datatransporttype'),
        ),
    ]
