# Generated by Django 5.0.2 on 2024-03-13 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0023_sourcesystem_transport_in_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdcreceivingsystem',
            old_name='other_supported_data_input_types',
            new_name='data_input_other_types',
        ),
        migrations.RenameField(
            model_name='cdcreceivingsystem',
            old_name='main_data_input_type',
            new_name='data_input_type',
        ),
        migrations.RemoveField(
            model_name='cdcreceivingsystem',
            name='main_data_input_transport_type',
        ),
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='input_transport_other_types',
            field=models.ManyToManyField(blank=True, related_name='cdc_other_supported_input_types', to='report_metadata.datatransporttype'),
        ),
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='input_transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.datatransporttype', verbose_name='Input Transport Type'),
        ),
    ]
