# Generated by Django 5.0.2 on 2024-03-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0024_rename_other_supported_data_input_types_cdcreceivingsystem_data_input_other_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdcreceivingsystem',
            old_name='data_input_other_types',
            new_name='input_data_other_types',
        ),
        migrations.RenameField(
            model_name='cdcreceivingsystem',
            old_name='data_input_type',
            new_name='input_data_type',
        ),
    ]
