# Generated by Django 5.0.2 on 2024-03-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0025_rename_data_input_other_types_cdcreceivingsystem_input_data_other_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcesystem',
            old_name='other_supported_data_input_types',
            new_name='input_data_other_types',
        ),
        migrations.RenameField(
            model_name='sourcesystem',
            old_name='main_data_input_type',
            new_name='input_data_type',
        ),
        migrations.RenameField(
            model_name='sourcesystem',
            old_name='other_supported_data_ouput_types',
            new_name='output_data_other_types',
        ),
        migrations.RenameField(
            model_name='sourcesystem',
            old_name='main_data_output_type',
            new_name='output_data_type',
        ),
    ]
