# Generated by Django 5.0.2 on 2024-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0029_intermediarysoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='program_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.programareatype'),
        ),
    ]
