# Generated by Django 5.0.2 on 2024-03-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0030_connection_program_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdcorganization',
            options={'ordering': ['code'], 'verbose_name': 'CDC Organization or Program', 'verbose_name_plural': 'CDC Organizations or Programs'},
        ),
        migrations.AlterModelOptions(
            name='cdcreceivingsoftware',
            options={'ordering': ['code'], 'verbose_name': 'Software: CDC Recipient', 'verbose_name_plural': 'Software: CDC Recipients'},
        ),
        migrations.AlterModelOptions(
            name='cdcreceivingsystem',
            options={'ordering': ['code'], 'verbose_name': 'System: CDC Recipient', 'verbose_name_plural': 'Systems: CDC Recipients'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['partner'], 'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='intermediarysoftware',
            options={'ordering': ['code'], 'verbose_name': 'Software:  Intermediary', 'verbose_name_plural': 'Software: Intermediaries'},
        ),
        migrations.AlterModelOptions(
            name='intermediarysystem',
            options={'ordering': ['code'], 'verbose_name': 'System: Intermediary', 'verbose_name_plural': 'Systems: Intermediaries'},
        ),
        migrations.AlterModelOptions(
            name='jurisdiction',
            options={'ordering': ['code'], 'verbose_name': 'Jurisdiction', 'verbose_name_plural': 'Jurisdictions'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='sourcesoftware',
            options={'ordering': ['code'], 'verbose_name': 'Software: Data Source', 'verbose_name_plural': 'Software: Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'ordering': ['code'], 'verbose_name': 'System: Data Source', 'verbose_name_plural': 'Systems: Data Sources'},
        ),
    ]
