# Generated by Django 5.0.2 on 2024-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0031_alter_cdcorganization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmetamessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='patient_dob_mobilephone_hash',
            new_name='mrn_and_node_hash',
        ),
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='fhir_bundle_payload_url',
            new_name='source_fhir_bundle_payload_url',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='bscrypt_salt',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='bscrypt_salt_rounds',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='bscrypt_salt_strategy',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='next_bscrypt_salt',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='next_origin_id',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='previous_bscrypt_salt',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='previous_origin_id',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='retired_bscrypt_salts',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='retired_origin_ids',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='rotate_origin_id',
        ),
        migrations.RemoveField(
            model_name='jurisdiction',
            name='rotate_shared_bscrypt_salt',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_address_city',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_address_line_1',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_address_line_2',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_first_name',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_last_name',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_middle_initial',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_middle_name',
        ),
        migrations.RemoveField(
            model_name='rmetamessage',
            name='patient_ssn',
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_dob_and_mobilephone_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_dob_email_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='patient_email_and_mobilephone_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='source_system_case_report_link_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='rmetamessage',
            name='link_to_prev_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Link to the first message_id for a given case/person.', max_length=36),
        ),
    ]
