# Generated by Django 5.0.2 on 2024-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0033_personhashtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personhashtype',
            options={'verbose_name': 'Types: Person Hash', 'verbose_name_plural': 'Types: People Hashes'},
        ),
        migrations.RemoveField(
            model_name='personhashtype',
            name='prefix',
        ),
        migrations.AddField(
            model_name='personhashtype',
            name='bcrypt_salt',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='personhashtype',
            name='pepper_prefix',
            field=models.CharField(blank=True, default='', help_text='Prepend this text to the value to be hashed.', max_length=255),
        ),
    ]
