# Generated by Django 5.0.2 on 2024-03-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0034_alter_personhashtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhashtype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
