# Generated by Django 5.0.2 on 2024-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0036_alter_personhashtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personhashtype',
            name='series',
            field=models.SmallIntegerField(default=0),
        ),
    ]
