# Generated by Django 5.0.2 on 2024-03-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0037_alter_personhashtype_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmetamessage',
            name='source_patient_id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.patientidtype'),
        ),
    ]
