# Generated by Django 5.0.2 on 2024-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0039_alter_rmetamessage_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmetamessage',
            name='link_to_prev_message_id',
        ),
        migrations.AddField(
            model_name='rmetamessage',
            name='initial_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Link to the initial message_id for a given case/person.', max_length=36),
        ),
    ]
