# Generated by Django 5.0.2 on 2024-03-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0040_remove_rmetamessage_link_to_prev_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmetamessage',
            name='cdc_payload_csv',
        ),
    ]
