# Generated by Django 5.0.2 on 2024-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0041_remove_rmetamessage_cdc_payload_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmetamessage',
            name='encompasing_encounter_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Link to the initial message_id for a given case/person.', max_length=64),
        ),
    ]
