# Generated by Django 5.0.2 on 2024-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0042_rmetamessage_encompasing_encounter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmetamessage',
            name='cdc_payload_json',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
