# Generated by Django 5.0.2 on 2024-03-21 15:18

import django.db.models.deletion
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0044_remove_sourcesystem_is_intermediary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='jurasdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.jurisdiction'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='state',
            field=localflavor.us.models.USPostalCodeField(blank=True, default='', max_length=2),
        ),
    ]
