# Generated by Django 5.0.2 on 2024-03-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0046_alter_sourcesystem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'ordering': ['jurisdiction__code', 'program_area'], 'verbose_name': 'System: Data Source', 'verbose_name_plural': 'Systems: Data Sources'},
        ),
    ]
