# Generated by Django 5.0.2 on 2024-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0047_alter_sourcesystem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'ordering': ['jurisdiction__code', 'program_areas__code'], 'verbose_name': 'System: Data Source', 'verbose_name_plural': 'Systems: Data Sources'},
        ),
        migrations.RemoveField(
            model_name='sourcesystem',
            name='program_area',
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='program_areas',
            field=models.ManyToManyField(blank=True, null=True, to='report_metadata.programareatype'),
        ),
    ]
