# Generated by Django 5.0.2 on 2024-03-22 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0049_alter_sourcesystem_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcesystem',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_metadata.sourcesoftware'),
        ),
    ]
