# Generated by Django 5.0.2 on 2024-03-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0050_alter_sourcesystem_software'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rmetamessage',
            options={'verbose_name': 'API Message', 'verbose_name_plural': 'API Messages'},
        ),
        migrations.AlterModelOptions(
            name='sourcesystem',
            options={'ordering': ['jurisdiction__code'], 'verbose_name': 'System: Data Source', 'verbose_name_plural': 'Systems: Data Sources'},
        ),
    ]
