# Generated by Django 5.0.2 on 2024-03-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0051_alter_rmetamessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InergrationEngineSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_poc', models.TextField(blank=True, default='', max_length=2048, verbose_name='Vendor Point of Contact')),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Software: Inergration Engine',
                'verbose_name_plural': 'Software: Inergration Engines',
                'ordering': ['code'],
            },
        ),
        migrations.RenameField(
            model_name='rmetamessage',
            old_name='encompasing_encounter_id',
            new_name='encompassing_encounter_id',
        ),
        migrations.AlterField(
            model_name='sourcesystem',
            name='program_areas',
            field=models.ManyToManyField(blank=True, to='report_metadata.programareatype'),
        ),
        migrations.CreateModel(
            name='InergrationEngineSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_poc', models.TextField(blank=True, default='', max_length=2048, verbose_name='Vendor Point of Contact')),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('input_data_other_types', models.ManyToManyField(blank=True, related_name='inergration_engine_input_data_other_types', to='report_metadata.healthdatatype')),
                ('input_data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_main_data_input_type', to='report_metadata.healthdatatype')),
                ('input_transport_other_types', models.ManyToManyField(blank=True, related_name='inergration_engine_import_transport_other_types', to='report_metadata.datatransporttype')),
                ('input_transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_transport_in', to='report_metadata.datatransporttype')),
                ('output_data_other_types', models.ManyToManyField(blank=True, related_name='inergration_engine_other_supported_output_data_types', to='report_metadata.healthdatatype')),
                ('output_data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_data_output_type', to='report_metadata.healthdatatype')),
                ('output_transport_other_types', models.ManyToManyField(blank=True, related_name='inergration_engine_output_data_other_types', to='report_metadata.datatransporttype')),
                ('output_transport_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_ransport_out', to='report_metadata.datatransporttype')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_software', to='report_metadata.intermediarysoftware')),
                ('source_system', models.ForeignKey(blank=True, help_text='Leave blank if original source (ie. not an intermediary system)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_source_system', to='report_metadata.sourcesoftware')),
            ],
            options={
                'verbose_name': 'System: Inergration Engine',
                'verbose_name_plural': 'Systems: Inergration Engines',
                'ordering': ['code'],
            },
        ),
    ]
