# Generated by Django 5.0.2 on 2024-03-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0052_inergrationenginesoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='integration_engine_systems',
            field=models.ManyToManyField(blank=True, related_name='cdcreceivingsystem_intermediary_systems', to='report_metadata.inergrationenginesystem'),
        ),
        migrations.AddField(
            model_name='cdcreceivingsystem',
            name='intermediary_systems',
            field=models.ManyToManyField(blank=True, related_name='cdcreceivingsystem_intermediary_systems', to='report_metadata.intermediarysystem'),
        ),
        migrations.AddField(
            model_name='connection',
            name='integration_engine_systems',
            field=models.ManyToManyField(blank=True, related_name='connection_intermediary_systems', to='report_metadata.inergrationenginesystem'),
        ),
        migrations.AddField(
            model_name='connection',
            name='intermediary_systems',
            field=models.ManyToManyField(blank=True, related_name='connection_intermediary_systems', to='report_metadata.intermediarysystem'),
        ),
    ]
