# Generated by Django 5.0.2 on 2024-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0053_cdcreceivingsystem_integration_engine_systems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcreceivingsystem',
            name='integration_engine_systems',
            field=models.ManyToManyField(blank=True, related_name='cdcreceivingsystem_integration_systems', to='report_metadata.inergrationenginesystem'),
        ),
    ]
