# Generated by Django 5.0.2 on 2024-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0054_alter_cdcreceivingsystem_integration_engine_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='integration_engine_systems',
            field=models.ManyToManyField(blank=True, related_name='sourcesystem_integration_systems', to='report_metadata.inergrationenginesystem'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='intermediary_systems',
            field=models.ManyToManyField(blank=True, related_name='sourcesystem_intermediary_systems', to='report_metadata.intermediarysystem'),
        ),
    ]
