# Generated by Django 5.0.2 on 2024-03-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0055_sourcesystem_integration_engine_systems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inergrationenginesystem',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_software', to='report_metadata.intermediarysoftware'),
        ),
        migrations.AlterField(
            model_name='intermediarysystem',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intermediary_software', to='report_metadata.intermediarysoftware'),
        ),
    ]
