# Generated by Django 5.0.2 on 2024-03-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0056_alter_inergrationenginesystem_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inergrationenginesystem',
            old_name='software',
            new_name='integration_engine_software',
        ),
        migrations.RenameField(
            model_name='intermediarysystem',
            old_name='software',
            new_name='intermediary_software',
        ),
        migrations.AlterField(
            model_name='inergrationenginesystem',
            name='source_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inergration_engine_source_system', to='report_metadata.sourcesoftware'),
        ),
    ]
