# Generated by Django 5.0.2 on 2024-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0059_requestaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaccess',
            name='math_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
