# Generated by Django 5.0.2 on 2024-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_metadata', '0060_alter_requestaccess_math_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestaccess',
            name='notes',
            field=models.TextField(blank=True, help_text='Please provide any additional information that may be helpful in processing your request.', null=True),
        ),
    ]
