# Generated by Django 5.0.9 on 2025-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0003_alter_dataelement_code_alter_dataelement_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='data_element_identifier_csv',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
