# Generated by Django 5.0.9 on 2025-01-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0004_alter_dataelement_data_element_identifier_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='OID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(db_index=True, max_length=64)),
                ('common_name', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('data_element_identifier_csv', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('code_display', models.CharField(blank=True, max_length=200)),
                ('code_system', models.CharField(blank=True, max_length=200)),
                ('code_system_name', models.CharField(blank=True, max_length=200)),
                ('code_system_version', models.CharField(blank=True, max_length=200)),
                ('fhir_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fhir_code_display', models.CharField(blank=True, max_length=200)),
                ('fhir_code_system', models.CharField(blank=True, max_length=200)),
                ('fhir_code_system_name', models.CharField(blank=True, max_length=200)),
                ('fhir_code_system_version', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
