# Generated by Django 5.0.9 on 2025-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0005_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oid',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
