# Generated by Django 5.0.9 on 2025-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0006_oid_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_element_name', models.CharField(blank=True, max_length=200)),
                ('data_element_identifier_csv', models.CharField(blank=True, max_length=200)),
                ('common_name', models.CharField(blank=True, max_length=200)),
                ('oid', models.CharField(blank=True, max_length=100)),
                ('data_element_description', models.CharField(blank=True, max_length=200)),
                ('data_element_type', models.CharField(blank=True, max_length=200)),
                ('cdc_priority', models.CharField(blank=True, max_length=1)),
                ('may_repeat', models.CharField(blank=True, max_length=64)),
                ('value_set_name', models.CharField(blank=True, max_length=200)),
                ('phinvads_hyperlink', models.CharField(blank=True, max_length=200)),
                ('phinvads_fhir_hyperlink', models.CharField(blank=True, max_length=200)),
                ('static_csv_hyperlink', models.CharField(blank=True, max_length=200)),
                ('value_set_code', models.CharField(blank=True, max_length=200)),
                ('repeating_group_element', models.CharField(blank=True, max_length=200)),
                ('repeating_group_name', models.CharField(blank=True, max_length=200)),
                ('csv_implementation_notes', models.TextField(blank=True)),
                ('sample_value', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='oid',
            options={'verbose_name': 'OID', 'verbose_name_plural': 'OIDs'},
        ),
    ]
