# Generated by Django 5.0.9 on 2025-01-21 22:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0007_mdn_alter_oid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdn',
            options={'verbose_name': 'MDN Data Element', 'verbose_name_plural': 'MDN Data Elements'},
        ),
        migrations.AddField(
            model_name='mdn',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdn',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mdn',
            name='cdc_priority',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
