# Generated by Django 5.0.9 on 2025-01-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0008_alter_mdn_options_mdn_date_created_mdn_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oid',
            options={'verbose_name': 'OID + Code Value', 'verbose_name_plural': 'OID + Code Values'},
        ),
    ]
