# Generated by Django 5.0.9 on 2025-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0009_alter_oid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdn',
            name='pa',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
