# Generated by Django 5.0.9 on 2025-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0010_mdn_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdn',
            name='static_json_hyperlink',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
