# Generated by Django 5.0.9 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0011_mdn_static_json_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdn',
            name='static_json_api',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
