# Generated by Django 5.1.10 on 2025-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0012_mdn_static_json_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdn',
            name='fhir_api',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mdn',
            name='fhir_body',
            field=models.TextField(blank=True),
        ),
    ]
