# Generated by Django 5.1.10 on 2025-07-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophv', '0013_mdn_fhir_api_mdn_fhir_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdn',
            name='csv_body',
            field=models.TextField(blank=True),
        ),
    ]
