# Generated by Django 5.0.9 on 2025-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cri_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contributing Agency Identifier 1'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cri_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contributing Agency Identifier 2'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cri_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contributing Agency Identifier 3'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cri_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contributing Agency Identifier 4'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cri_5',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contributing Agency Identifier 5'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status_url',
            field=models.URLField(blank=True, default='http://localhost:8000/frontdoor/transaction/status/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tcn',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Transaction Control Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tcr',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Transaction Control Reference'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=16),
        ),
    ]
