# Generated by Django 5.0.9 on 2025-01-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0002_alter_origin_code_alter_transaction_cri_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='submission',
            new_name='transaction',
        ),
    ]
