# Generated by Django 5.0.9 on 2025-02-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0004_facility_transactiontype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='facility_id',
            new_name='facility',
        ),
        migrations.AddField(
            model_name='origin',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontdoor.facility'),
        ),
    ]
