# Generated by Django 5.0.9 on 2025-03-04 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0005_alter_facility_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionreceipt',
            options={'verbose_name': 'Receipts', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AddField(
            model_name='submission',
            name='postal_code_facility',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='postal_code_subject',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='destination_tcn',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text="The server's tranaction control number, generated automatically.", max_length=100, verbose_name='Destination Transaction Control Number'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter_agency', to='frontdoor.submitter', verbose_name='Origin Agency Identifier'),
        ),
    ]
