# Generated by Django 5.0.9 on 2025-03-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0006_alter_submissionreceipt_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitter_tcn',
            new_name='transaction_control_number',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submitter_tcr',
            new_name='transaction_control_reference',
        ),
    ]
