# Generated by Django 5.0.9 on 2025-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0007_rename_submitter_tcn_submission_transaction_control_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='fhir_bundle_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='hl7_parsed_message_json',
            field=models.TextField(blank=True),
        ),
    ]
