# Generated by Django 5.0.9 on 2025-03-05 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0008_submission_fhir_bundle_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='postal_code_facility',
            new_name='facility_postal_code',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='postal_code_subject',
            new_name='subject_postal_code',
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='frontdoor.facility'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
