# Generated by Django 5.0.9 on 2025-03-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0009_rename_postal_code_facility_submission_facility_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
