# Generated by Django 5.0.9 on 2025-03-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0011_alter_submission_transaction_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='facility_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
