# Generated by Django 5.0.9 on 2025-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0012_submission_facility_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='inbound_transmission_type',
            field=models.CharField(blank=True, choices=[('REST-SUBMIT-API', 'Base Submission API'), ('FHIR-PROCESS-MESSAGE-API', 'FHIR Bundle Submission via process message endpoint.'), ('FILE-DROP', 'File/folder drop such as SFTP or AWS S3'), ('WEB-FORM', 'Front Door Web Forms'), ('EMAIL-ENCRYPTED', 'Encrypted Email'), ('EMAIL-DIRECT', 'Submitted using DIRECT Protocol')], max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
