# Generated by Django 5.0.9 on 2025-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0013_submission_inbound_transmission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duplicate_payload',
            field=models.BooleanField(default=False),
        ),
    ]
