# Generated by Django 5.0.9 on 2025-03-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0014_submission_duplicate_payload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='origin',
            options={'verbose_name': 'Agency ID', 'verbose_name_plural': 'Agency IDs'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='duplicate_payload',
        ),
        migrations.AddField(
            model_name='submission',
            name='unique_payload',
            field=models.BooleanField(default=True),
        ),
    ]
