# Generated by Django 5.0.9 on 2025-04-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0015_alter_origin_options_and_more'),
        ('report_metadata', '0062_alter_requestaccess_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='person_id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_metadata.patientidtype'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='inbound_source_type',
            field=models.CharField(blank=True, choices=[('REST-SUBMIT-API', 'Base Submission API'), ('FHIR-PROCESS-MESSAGE-API', 'FHIR Bundle Submission via process message endpoint.'), ('FILE-DROP', 'File/folder drop such as SFTP or AWS S3'), ('WEB-FORM', 'Front Door Web Forms'), ('EMAIL-ENCRYPTED', 'Encrypted Email'), ('EMAIL-DIRECT', 'Submitted using DIRECT Protocol')], default='REST-SUBMIT-API', max_length=120),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='bef92c85-4404-4421-a2e8-f30761e328a3', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
