# Generated by Django 5.0.9 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0016_submission_person_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='0ac167b4-326b-4caf-838b-a5912287d62b', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
