# Generated by Django 5.0.9 on 2025-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0017_alter_submission_transaction_control_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='onecdc_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='onecdc_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='2619786c-510c-464a-ac44-db0ba7cdc54a', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
