# Generated by Django 5.0.9 on 2025-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0018_submission_onecdc_status_submission_onecdc_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='onecdc_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='eef7b1b9-8d3e-4de7-ae4b-46d636fb208d', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
