# Generated by Django 5.0.9 on 2025-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0019_submission_onecdc_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='dc63dc5d-2b26-4a28-870a-3b63b0624068', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
