# Generated by Django 5.0.9 on 2025-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0020_alter_submission_transaction_control_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='758c631b-5b83-4c84-bf6e-53fbae7e9a0d', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
