# Generated by Django 5.0.9 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdoor', '0021_alter_submission_transaction_control_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='transaction_control_reference',
            field=models.CharField(blank=True, db_index=True, default='93772745-e7ac-47a7-85e5-ad598612b033', max_length=64, null=True, verbose_name='Transaction Control Reference'),
        ),
    ]
