# Generated by Django 5.0.2 on 2024-04-01 14:27

import localflavor.us.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashlink', models.CharField(db_index=True, default=uuid.uuid4, max_length=36, unique=True)),
                ('dob_and_mobilephone_hash', models.CharField(blank=True, default='', max_length=64)),
                ('email_and_mobilephone_hash', models.CharField(blank=True, default='', max_length=64)),
                ('dob_and_email_hash', models.CharField(blank=True, default='', max_length=64)),
                ('insurance_plan_and_insurance_member_hash', models.CharField(blank=True, default='', max_length=64)),
                ('mrn_and_node_hash', models.CharField(blank=True, default='', max_length=64)),
                ('initial_message_id', models.CharField(blank=True, db_index=True, default='', help_text='Link to the initial message_id for a given case/person.', max_length=36)),
                ('encompassing_encounter_id', models.CharField(blank=True, db_index=True, default='', help_text='Link to the initial message_id for a given case/person.', max_length=64)),
                ('source_system_case_report_type', models.CharField(blank=True, choices=[('SUSPECTED', 'SUSPECTED'), ('PROBABLE', 'PROBABLE'), ('CONFIRMED', 'CONFIRMED')], db_index=True, default='', max_length=15)),
                ('source_system', models.CharField(blank=True, default='', max_length=36)),
                ('cdc_receiving_system', models.CharField(blank=True, default='', max_length=36)),
                ('report_url', models.URLField(blank=True, default='', max_length=512)),
                ('reportable_condition_flag', models.BooleanField(default=False, null=True)),
                ('notifiable_condition_flag', models.BooleanField(default=False, null=True)),
                ('current_case_status', models.CharField(blank=True, choices=[('SUSPECTED', 'SUSPECTED'), ('PROBABLE', 'PROBABLE'), ('CONFIRMED', 'CONFIRMED')], db_index=True, default='', max_length=15)),
                ('final_case_status', models.CharField(blank=True, choices=[('SUSPECTED', 'SUSPECTED'), ('PROBABLE', 'PROBABLE'), ('CONFIRMED', 'CONFIRMED')], db_index=True, default='', max_length=15)),
                ('final_case_status_date', models.DateField(blank=True, null=True)),
                ('source_system_node', models.CharField(blank=True, max_length=36)),
                ('source_system_transaction_id', models.CharField(blank=True, default='', max_length=36)),
                ('source_system_initial_case_report_id', models.CharField(blank=True, default='', max_length=36)),
                ('source_system_case_report_link_id', models.CharField(blank=True, default='', max_length=36)),
                ('source_systems_patient_id_issuer', models.CharField(blank=True, default='', max_length=36)),
                ('source_data_format', models.CharField(blank=True, default='', max_length=36)),
                ('source_data_transport_type', models.CharField(blank=True, default='', max_length=36)),
                ('test_ordered_test_loinc_code', models.CharField(blank=True, default='', max_length=36)),
                ('test_ordered_test_device_identifier', models.CharField(blank=True, default='', max_length=36)),
                ('test_ordered_result_loinc_code', models.CharField(blank=True, default='', max_length=36)),
                ('test_ordered_snomed_code', models.CharField(blank=True, default='', max_length=36)),
                ('test_ordered_result_date', models.DateField(blank=True, null=True)),
                ('test_ordered_accession_num_or_specimen_id', models.CharField(blank=True, default='', max_length=36)),
                ('cdc_receiving_system_status', models.CharField(blank=True, default='', max_length=36)),
                ('cdc_receiving_system_url', models.URLField(blank=True, max_length=512, null=True)),
                ('patient_first_name', models.CharField(blank=True, default='', max_length=128)),
                ('patient_last_name', models.CharField(blank=True, default='', max_length=128)),
                ('patient_date_of_birth', models.DateField(blank=True, null=True)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('patient_race', models.CharField(blank=True, default='', max_length=36)),
                ('patient_ethnicity', models.CharField(blank=True, default='', max_length=36)),
                ('patient_sex', models.CharField(blank=True, default='', max_length=36)),
                ('patient_address_state', localflavor.us.models.USPostalCodeField(blank=True, default='', max_length=2)),
                ('patient_residence_zip_code', models.CharField(blank=True, default='', max_length=36)),
                ('patient_residence_county', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('sanitized_payload', models.TextField(blank=True, default='{}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonymized Message',
                'verbose_name_plural': 'Anonymized Messages',
            },
        ),
    ]
