# Generated by Django 5.0.2 on 2024-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizedmessage',
            name='dob_and_fn_and_ln_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
