# Generated by Django 5.0.2 on 2024-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouser', '0003_rename_hashlink_anonymizedmessage_random_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymizedmessage',
            old_name='mrn_and_node_hash',
            new_name='source_system_mrn_and_node_hash',
        ),
        migrations.AddField(
            model_name='anonymizedmessage',
            name='patient_email',
            field=models.EmailField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='anonymizedmessage',
            name='source_system_mrn',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
