# Generated by Django 5.0.2 on 2024-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouser', '0004_rename_mrn_and_node_hash_anonymizedmessage_source_system_mrn_and_node_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizedmessage',
            name='patient_insurance_member_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='anonymizedmessage',
            name='patient_insurance_plan_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
