# Generated by Django 5.0.2 on 2024-04-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouser', '0005_anonymizedmessage_patient_insurance_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymizedmessage',
            name='sanitized_payload',
        ),
    ]
