# Generated by Django 5.0.9 on 2024-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=100)),
                ('cause_of_death', models.CharField(max_length=100)),
                ('informant_name', models.CharField(max_length=100)),
                ('informant_relationship', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
