# Generated by Django 5.0.2 on 2024-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashcow', '0002_rename_message_id_hashedmessage_hashlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashedmessage',
            options={'verbose_name': 'Hashed Message', 'verbose_name_plural': 'Hashed Messages'},
        ),
        migrations.RemoveField(
            model_name='hashedmessage',
            name='cdc_receiving_case_report_id',
        ),
        migrations.RemoveField(
            model_name='hashedmessage',
            name='source_data_payload_pointer',
        ),
        migrations.RemoveField(
            model_name='hashedmessage',
            name='source_fhir_bundle_payload_url',
        ),
        migrations.RemoveField(
            model_name='hashedmessage',
            name='source_patient_id_issuer',
        ),
        migrations.RemoveField(
            model_name='hashedmessage',
            name='source_patient_id_type',
        ),
        migrations.AddField(
            model_name='hashedmessage',
            name='dob_and_fn_and_ln_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
