# Generated by Django 5.0.2 on 2024-11-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('report_metadata', '0062_alter_requestaccess_notes'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('reviewers', models.ManyToManyField(related_name='reviewers', to='auth.group')),
                ('submitters', models.ManyToManyField(related_name='submitters', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Incomming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_agency_identifier', models.CharField(max_length=100)),
                ('intermediate_agency_identifier', models.CharField(max_length=100)),
                ('destination_agency_identifier', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('payload', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('data_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facade.datastream')),
                ('payload_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_metadata.healthdatatype')),
            ],
        ),
    ]
