# Generated by Django 5.0.9 on 2024-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomming',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED')], default='ACCEPTED', max_length=100),
            preserve_default=False,
        ),
    ]
