# Generated by Django 5.0.9 on 2024-11-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_incomming_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomming',
            name='destination_agency_identifier',
            field=models.CharField(default='CDC-1CDP-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='incomming',
            name='intermediate_agency_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
