# Generated by Django 5.0.9 on 2024-11-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_datastream_allowable_payload_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastream',
            name='submitters',
        ),
    ]
