# Generated by Django 5.0.9 on 2024-11-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_incomming_destination_agency_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomming',
            name='multiple_entries',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='incomming',
            name='payload_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='incomming',
            name='payload',
            field=models.TextField(blank=True),
        ),
    ]
