# Generated by Django 5.0.9 on 2024-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_remove_datastream_submitters'),
        ('report_metadata', '0062_alter_requestaccess_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastream',
            name='program_area',
            field=models.ManyToManyField(blank=True, related_name='program_area', to='report_metadata.programareatype'),
        ),
    ]
