# Generated by Django 5.0.9 on 2024-11-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_datastream_program_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='response_json',
            field=models.TextField(blank=True),
        ),
    ]
